{% set version = "2.7.1" %}

package:
  name: python-hdfs
  version: {{ version }}

source:
  fn: hdfs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/hdfs/hdfs-{{ version }}.tar.gz
  sha256: 9cd8ac73e03c83f9e588a5ee6ec9b1e953fb652ad8dd03da337a17de34a4c2cb

build:
  noarch: python
  number: 0
  entry_points:
    - hdfscli = hdfs.__main__:main
    - hdfscli-avro = hdfs.ext.avro.__main__:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - docopt
    - fastavro >=0.21.19
    - pandas >=0.14.1
    - requests >=2.7.0
    - requests-kerberos >=0.7.0
    - six >=1.9.0

test:
  imports:
    - hdfs
    - hdfs.ext
    - hdfs.ext.avro
    - hdfs.ext.dataframe
    - hdfs.ext.kerberos

  commands:
    - hdfscli --help
    - hdfscli-avro --help

about:
  home: http://hdfscli.readthedocs.org
  license: MIT
  license_file: LICENSE
  summary: 'HdfsCLI: API and command line interface for HDFS.'

extra:
  recipe-maintainers:
    - xylar
    - mariusvniekerk
    - parente
    - FernandezMathieu
    - efiop
